global:
  scrape_interval:     15s
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'redis'
    scrape_interval: 1s
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'apps'
    scrape_interval: 5s
    static_configs:
      - targets: ['web:5000']
